[package]
name = "mupen64plus"
version = "0.1.0"
edition = "2018"
license = "GPL-2.0"

[dependencies]
mupen64plus-sys = "*"
libloading = "*"
thiserror = "1"
semver = "1"
bitflags = "1"
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"
